#!/usr/bin/env python3
"""
Based on: http://filmicworlds.com/blog/command-line-photogrammetry-with-alicevision/
"""

from argparse import ArgumentParser
from functools import partial
from pathlib import Path
from subprocess import run

LD_LIBRARY_PATH = Path.home() / ".local/Meshroom-2020.1.0/aliceVision/lib/"

CAMERA_INITIALIZATION_DIRNAME = "CameraInitialization"
CAMERA_SFM_FILENAME = "cameraInit.sfm"

FEATURE_EXTRACTION_DIRNAME = "FeatureExtraction"


def run_cmd_and_print_results(verbose, silent, cmd, step_name):

    if verbose:
        print("-" * 16)

    if not silent:
        print("Starting the ", step_name, "step...", end="")

    env = {"LD_LIBRARY_PATH": LD_LIBRARY_PATH}
    cmd_result = run(cmd, capture_output=True, env=env)

    if not silent:
        print("done")

    if verbose:
        cmd_strs = [str(c) if len(str(c)) > 0 else '""' for c in cmd]
        print("Running command:", " ".join(cmd_strs))
        print(cmd_result.stdout.decode("utf-8"))

    if cmd_result.returncode != 0:
        print(cmd_result.stderr.decode("utf-8"))

    return cmd_result.returncode == 0


def initialize_camera(output: Path, meshroom: Path, image: Path, handle_cmd) -> bool:

    odir = output / CAMERA_INITIALIZATION_DIRNAME
    odir.mkdir(exist_ok=True)

    camera_init_bin = meshroom / "aliceVision" / "bin" / "aliceVision_cameraInit"

    cmd = [
        camera_init_bin,
        "--imageFolder",
        image,
        "--sensorDatabase",
        "",
        "--output",
        odir / CAMERA_SFM_FILENAME,
        "--defaultFieldOfView",
        "45.0",
        "--verboseLevel",
        "info",
        "--allowSingleView",
        "1",
    ]

    # Return True if operation is successful
    return handle_cmd(cmd, "camera initialization")


def extract_features(output: Path, meshroom: Path, num_images: int, handle_cmd) -> bool:

    odir = output / FEATURE_EXTRACTION_DIRNAME
    odir.mkdir(exist_ok=True)

    camera_sfm_filepath = output / CAMERA_INITIALIZATION_DIRNAME / CAMERA_SFM_FILENAME

    feature_extraction_bin = (
        meshroom / "aliceVision" / "bin" / "aliceVision_featureExtraction"
    )

    cmd = [
        feature_extraction_bin,
        "--input",
        camera_sfm_filepath,
        "--output",
        odir,
        "--describerTypes",
        "sift",
        "--verboseLevel",
        "info",
        "--describerPreset",
        "normal",
        "--rangeStart",
        "0",
        "--rangeSize",
        str(num_images),
    ]

    # Return True if operation is successful
    return handle_cmd(cmd, "feature extraction")


def main():
    aparser = ArgumentParser("Run AlliceVision from the command line.")
    aparser.add_argument(
        "meshroom_dir", type=Path, help="Path to the Meshroom directory."
    )
    aparser.add_argument("image_dir", type=Path)
    aparser.add_argument("output_dir", type=Path)
    aparser.add_argument(
        "--verbose", action="store_true", help="Print information for each step."
    )
    aparser.add_argument("--silent", action="store_true", help="Suppress all printing.")
    aparser.add_argument("--run_all", help="Run all Photogrammetry steps.")
    args = aparser.parse_args()

    num_images = len([img for img in Path(args.image_dir).glob("*") if img.is_file()])

    if not args.silent:
        print("Configuration:")
        print(f" Output directory   : {args.output_dir}")
        print(f" Image directory    : {args.image_dir}")
        print(f" Meshroom directory : {args.meshroom_dir}")
        print(f" Number of images   : {num_images}")
        # print(f" Step to run        : {args.step_to_run}")
        # TODO: print steps

    # Create the output directory if it does not already exist
    Path(args.output_dir).mkdir(parents=True, exist_ok=True)

    # Create a function for handling printing (for convienence)
    handle_cmd = partial(run_cmd_and_print_results, args.verbose, args.silent)

    # Run each step
    if not initialize_camera(
        args.output_dir, args.meshroom_dir, args.image_dir, handle_cmd
    ):
        raise SystemExit

    if not extract_features(args.output_dir, args.meshroom_dir, num_images, handle_cmd):
        raise SystemExit


if __name__ == "__main__":
    main()
